CREATE TABLE `cronogramas` (
	`id` int AUTO_INCREMENT NOT NULL,
	`simulationId` int NOT NULL,
	`mes` int NOT NULL,
	`dataParcela` varchar(10) NOT NULL,
	`saldoInicial` int NOT NULL,
	`juros` int NOT NULL,
	`amortizacao` int NOT NULL,
	`parcela` int NOT NULL,
	`custosFixos` int NOT NULL DEFAULT 0,
	`saldoFinal` int NOT NULL,
	`observacoes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `cronogramas_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `simulations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`descricaoOferta` text,
	`valorTotalOferta` int NOT NULL,
	`valorInvestido` int NOT NULL,
	`dataInicio` varchar(10) NOT NULL,
	`prazoMeses` int NOT NULL,
	`taxaJurosAa` int NOT NULL,
	`convencaoCalendario` varchar(20) NOT NULL DEFAULT 'civil/365',
	`tipoCapitalizacao` varchar(20) NOT NULL DEFAULT 'composta',
	`periodicidadeJuros` varchar(20) NOT NULL DEFAULT 'mensal',
	`periodicidadeAmortizacao` varchar(20) NOT NULL DEFAULT 'mensal',
	`carenciaJurosMeses` int NOT NULL DEFAULT 0,
	`carenciaPrincipalMeses` int NOT NULL DEFAULT 0,
	`capitalizarJurosEmCarencia` int NOT NULL DEFAULT 1,
	`amortizacaoMetodo` varchar(20) NOT NULL DEFAULT 'PRICE',
	`pagamentoMinimoValor` int,
	`taxaSetupFixaBrl` int NOT NULL DEFAULT 0,
	`feeSucessoPercentSobreCaptacao` int NOT NULL DEFAULT 0,
	`feeManutencaoMensalBrl` int NOT NULL DEFAULT 0,
	`taxaTransacaoPercent` int NOT NULL DEFAULT 0,
	`aliquotaImpostoRendaPercent` int NOT NULL DEFAULT 0,
	`identificadorInvestidor` varchar(100),
	`moedaReferencia` varchar(10) NOT NULL DEFAULT 'BRL',
	`totalJurosPagos` int NOT NULL DEFAULT 0,
	`totalAmortizado` int NOT NULL DEFAULT 0,
	`totalRecebido` int NOT NULL DEFAULT 0,
	`tirMensal` int,
	`tirAnual` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `simulations_id` PRIMARY KEY(`id`)
);
